arxivprep: Use braces around variables consistently
Trim whitespace at end of lines

diff --git a/arxivprep b/arxivprep
--- a/arxivprep
+++ b/arxivprep
@@ -17,12 +17,12 @@
 # Prepare tarball of tex document for arXiv submission, stripping any comments.
 #
 # Usage: arxivprep [TEXNAME[.tex]]
-# 
+#
 # If a TeX typesetter is available, arxivprep attempts to determine document
 # dependencies automatically by examining the list of input and output files
 # generated by the -recorder option of modern versions of latex (and pdflatex,
 # xelatex, lualatex, etc).
-# 
+#
 # If TEXNAME if specified it is used as the main document when determining
 # document dependencies. If omitted, document dependencies are determined from
 # the first .tex file (in alphanumeric order) in the current directory.
@@ -37,13 +37,13 @@
 # arxivprep respects the following environment variables:
 #
 # TYPESETTER  TeX typesetter used for automatic document dependency detection.
-#             Must support -recorder option. Defaults to pdflatex. 
+#             Must support -recorder option. Defaults to pdflatex.
 #
 # LATEXFLAGS  Additional command line flags passed to TYPESETTER.
 #
 # OUTFILE     Pathname of output tarball to be created.
 #
-# TMPDIR      Pathname to directory where to place temporary files. 
+# TMPDIR      Pathname to directory where to place temporary files.
 #
 # AUXDIR      Pathname to directory used to store auxiliary files generated
 #             during document dependency detection. Setting this environment
@@ -55,10 +55,10 @@
 #             files to be left in the specified directory.
 #
 # STRIPTEXCOMMENT Commandline used to invoke striptexcomments script.
-# 
+#
 # The following environment variables can be used to override automatically
 # detected document dependencies.
-# 
+#
 # INPUTS      List of files to include in tarball.
 #
 # TEXFILES    Tex files (.tex) to strip from comments and include in tarball.
@@ -79,12 +79,12 @@ readonly SCRIPTPATH=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null; pwd -P )
 readonly TYPESETTER=${TYPESETTER:-"pdflatex"}
 readonly LATEXFLAGS=${LATEXFLAGS:--halt-on-error -interaction=batchmode -draftmode}
 
-readonly OUTFILE=${OUTFILE:-$(basename $PWD)_arxiv.tar.gz}
-readonly TMPDIR=${TMPDIR:-/tmp}/$(basename $0).$$
+readonly OUTFILE=${OUTFILE:-$(basename ${PWD})_arxiv.tar.gz}
+readonly TMPDIR=${TMPDIR:-/tmp}/$(basename ${0}).$$
 readonly AUXDIR=${AUXDIR:-"${TMPDIR}/aux"}
 readonly TARDIR=${TARDIR:-"${TMPDIR}/tar"}
 
-readonly STRIPTEXCOMMENTS=${STRIPTEXCOMMENTS:-"python $SCRIPTPATH/striptexcomments --encoding utf-8"}
+readonly STRIPTEXCOMMENTS=${STRIPTEXCOMMENTS:-"python ${SCRIPTPATH}/striptexcomments --encoding utf-8"}
 
 # Error values
 readonly E_TYPESET_FAILED=250
@@ -106,7 +106,7 @@ warning() {
 
 cleanup() {
   if [[ -d "${TMPDIR}" ]]; then
-    rm -r "${TMPDIR}" || error $E_RM_FAILED "failed to remove '$TMPDIR'"
+    rm -r "${TMPDIR}" || error ${E_RM_FAILED} "failed to remove '${TMPDIR}'"
   fi
 }
 
@@ -116,12 +116,12 @@ main() {
 
   # Prepare temporary directory
   if [[ ! -d "${TMPDIR}" ]]; then
-    mkdir -p "${TMPDIR}" || error $E_MKDIR_FAILED "failed to create '$TMPDIR'"
+    mkdir -p "${TMPDIR}" || error ${E_MKDIR_FAILED} "failed to create '${TMPDIR}'"
   fi
-  
+
   # Run cleanup routine on exit
   trap cleanup EXIT
-  
+
   # Determine document dependencies automatically by examining the list of input
   # and output files generated by the -recorder option of modern versions of
   # latex (and pdflatex, xelatex, lualatex, etc). In (most) modern versions of
@@ -131,25 +131,25 @@ main() {
   if command -v "${TYPESETTER}" &> /dev/null; then  # Typesetter is available
     # Prepare directory for auxiliary files
     if [[ ! -d "${AUXDIR}" ]]; then
-      mkdir -p "${AUXDIR}" || error $E_MKDIR_FAILED "failed to create '$AUXDIR'"
+      mkdir -p "${AUXDIR}" || error ${E_MKDIR_FAILED} "failed to create '${AUXDIR}'"
     fi
-    
-    ${TYPESETTER} ${LATEXFLAGS} -recorder -output-directory "${AUXDIR}" "${texname}" > /dev/null || error $E_TYPESET_FAILED "failed to run '${TYPESETTER}'"
-    
+
+    ${TYPESETTER} ${LATEXFLAGS} -recorder -output-directory "${AUXDIR}" "${texname}" > /dev/null || error ${E_TYPESET_FAILED} "failed to run '${TYPESETTER}'"
+
     # Look for .bbl files for $texname. Bibliographies do no show up in recorded
     # dependencies before a .bbl file has been generated. If found, inject INPUT
     # line for .bbl in the .fls processing below.
     if [[ -f "${texname}.bbl" ]]; then
       local -r bblinput="INPUT ${texname}.bbl"
     fi
-    
+
     # Extract unique INPUT files in the current directory subtree
     local -r inputs=(${INPUTS:-$(awk '/^INPUT / && !/^INPUT [!\/]/ { sub(/^INPUT (\.\/)?/, ""); print }' "${AUXDIR}/${texname}.fls" <(echo "${bblinput}") | sort | uniq)})
-    
+
   else  # Typesetter is not available
     warning "${TYPESETTER} not found; using pattern matching to identify input files"
-    
-    local -r inputs=${INPUTS:-$(find $(dirname "$texname") -iname '*.tex' \
+
+    local -r inputs=${INPUTS:-$(find $(dirname "${texname}") -iname '*.tex' \
       -o -iname '*.bbl' \
       -o -iname '*.cls' \
       -o -iname '*.sty' \
@@ -158,16 +158,16 @@ main() {
       -o -iname '*.jpg' \
       -o -iname '*.png')}
   fi
-  
+
   local -r texfiles=(${TEXFILES:-$(printf -- '%s\n' "${inputs[@]}" | grep -E "\.tex$")})
   local -r bblfiles=(${BBLFILES:-$(printf -- '%s\n' "${inputs[@]}" | grep -E "\.bbl$")})
   local -r pkgfiles=(${PKGFILES:-$(printf -- '%s\n' "${inputs[@]}" | grep -E "\.cls$|\.sty$")})
   local -r figfiles=(${FIGFILES:-$(printf -- '%s\n' "${inputs[@]}" | grep -E "\.pdf$|\.jpeg$|\.jpg$|\.png$")})
-  
+
   # Process tex files
   for texfile in ${texfiles[@]}; do
-    mkdir -p $(dirname "$TARDIR/$texfile") || error $E_MKDIR_FAILED "failed to create '$(dirname "$TARDIR/$texfile")'"
-    $($STRIPTEXCOMMENTS "$texfile" > "$TARDIR/$texfile") || error $E_STRIPTEXCOMMENTS 'failed to strip comments from '$texfile''
+    mkdir -p $(dirname "${TARDIR}/${texfile}") || error ${E_MKDIR_FAILED} "failed to create '$(dirname "${TARDIR}/${texfile}")'"
+    ${STRIPTEXCOMMENTS} "${texfile}" > "${TARDIR}/${texfile}" || error ${E_STRIPTEXCOMMENTS} 'failed to strip comments from '${texfile}''
   done
 
   # Check for presence of bbl file
@@ -177,12 +177,12 @@ main() {
 
   # Copy other files to temporary directory
   for file in ${bblfiles[@]} ${pkgfiles[@]} ${figfiles[@]}; do
-    mkdir -p "$(dirname "${TARDIR}/${file}")" || error $E_MKDIR_FAILED "failed to create '$(dirname "${TARDIR}/${file}")'"
-    cp "${file}" "${TARDIR}/${file}" || error $E_CP_FAILED "failed to copy '${file}' to '${TARDIR}/${file}'"
+    mkdir -p "$(dirname "${TARDIR}/${file}")" || error ${E_MKDIR_FAILED} "failed to create '$(dirname "${TARDIR}/${file}")'"
+    cp "${file}" "${TARDIR}/${file}" || error ${E_CP_FAILED} "failed to copy '${file}' to '${TARDIR}/${file}'"
   done
 
   # Create tarball
-  tar czvf "$OUTFILE" -C "$TARDIR" . || error $E_TAR_FAILED "failed to create tarball '$OUTFILE'"
+  tar czvf "${OUTFILE}" -C "${TARDIR}" . || error ${E_TAR_FAILED} "failed to create tarball '${OUTFILE}'"
 }
 
 main "$@"
